- hosts: localhost
  pre_tasks:
  - name: Update apt
    become: true
    register: result
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - core
  - debug:
      var: result.stdout
  tasks:
  - import_tasks: tasks/ssh.yml
  - import_tasks: tasks/core.yml
  - import_tasks: tasks/zsh-setup.yml
  - import_tasks: tasks/neovim.yml
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/git-setup.yml
  - import_tasks: tasks/productivity-tools.yml
