- name: Installing stow
  apt: name=stow
  tags: dotfiles

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:Seergs/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - dotfiles

- name: Remove existing zshrc
  shell: "rm ~/.zshrc"
  tags: dotfiles

- name: Stow dotfiles
  shell: cd $HOME/dotfiles && ./setup
  register: result
  tags: dotfiles

- debug: msg="{{ result.stdout }}"

