- name: Ensure ssh directory exists
  file:
    dest: "~/.ssh/"
    mode: 0700
    state: directory
  tags: 
    - dotfiles
    - ssh

- name: Install ssh key
  copy:
    src: ".ssh/id_rsa"
    dest: "~/.ssh/id_rsa"    
    mode: 0600
  tags:
    - dotfiles
    - ssh

- name: Install public ssh key
  copy:
    src: ".ssh/id_rsa.pub"
    dest: "~/.ssh/id_rsa.pub"
    mode: 0644
  tags:
    - dotfiles
    - ssh

- name: Set authorized key
  authorized_key:
    user: root
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
